// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectoef;

#nullable disable

namespace projectoef.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20240924153136_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projectoef.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Importancia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("5d8c1bcb-4242-41ae-ac34-f44922c5bf6c"),
                            Importancia = 20,
                            Nombre = "Actividades Pendientes"
                        },
                        new
                        {
                            CategoriaId = new Guid("5d8c1bcb-4242-41ae-ac34-f44922c5bf02"),
                            Importancia = 50,
                            Nombre = "Actividades Personales"
                        });
                });

            modelBuilder.Entity("projectoef.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("5d8c1bcb-4242-41ae-ac34-f44922c5bf01"),
                            CategoriaId = new Guid("5d8c1bcb-4242-41ae-ac34-f44922c5bf6c"),
                            Descripcion = "Estudiar C# desde cero",
                            FechaCreacion = new DateTime(2024, 9, 24, 10, 31, 35, 827, DateTimeKind.Local).AddTicks(1006),
                            PrioridadTarea = 1,
                            Titulo = "Estudiar C#"
                        },
                        new
                        {
                            TareaId = new Guid("5d8c1bcb-4242-41ae-ac34-f44922c5bf05"),
                            CategoriaId = new Guid("5d8c1bcb-4242-41ae-ac34-f44922c5bf02"),
                            Descripcion = "Ver Netflix",
                            FechaCreacion = new DateTime(2024, 9, 24, 10, 31, 35, 828, DateTimeKind.Local).AddTicks(6326),
                            PrioridadTarea = 0,
                            Titulo = "Terminar de ver peliculas en Netflix"
                        });
                });

            modelBuilder.Entity("projectoef.Models.Tarea", b =>
                {
                    b.HasOne("projectoef.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("projectoef.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
